# Generated by Django 5.2.15 on 2026-07-14 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedProfileContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_bio', models.TextField(blank=True, default='')),
                ('generated_future_goals', models.TextField(blank=True, default='')),
                ('generated_looking_for', models.TextField(blank=True, default='')),
                ('style', models.CharField(default='friendly', max_length=20)),
                ('language', models.CharField(default='en', max_length=8)),
                ('traits', models.JSONField(blank=True, default=list)),
                ('source_fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('generation_version', models.PositiveSmallIntegerField(default=1)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generated profile content',
                'verbose_name_plural': 'Generated profile content',
            },
        ),
        migrations.CreateModel(
            name='SentenceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('interest', 'Interest'), ('occupation', 'Occupation'), ('education', 'Education'), ('lifestyle', 'Lifestyle'), ('location', 'Location'), ('religion', 'Religion'), ('personality', 'Personality'), ('connector', 'Connector'), ('opener', 'Opener'), ('closer', 'Closer'), ('future', 'Future goals'), ('looking', 'Looking for'), ('value', 'Values')], db_index=True, max_length=32)),
                ('subcategory', models.CharField(blank=True, db_index=True, default='', help_text='e.g. gym, travel, smoking:never, career, marriage', max_length=64)),
                ('text', models.TextField()),
                ('weight', models.PositiveSmallIntegerField(default=5)),
                ('language', models.CharField(choices=[('en', 'English'), ('ne', 'Nepali'), ('hi', 'Hindi')], db_index=True, default='en', max_length=8)),
                ('style', models.CharField(choices=[('any', 'Any / Neutral'), ('professional', 'Professional'), ('romantic', 'Romantic'), ('funny', 'Funny'), ('minimal', 'Minimal'), ('confident', 'Confident'), ('adventurous', 'Adventurous'), ('intellectual', 'Intellectual'), ('friendly', 'Friendly')], db_index=True, default='any', max_length=20)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'subcategory', '-weight', 'id'],
                'indexes': [models.Index(fields=['active', 'language', 'category', 'subcategory'], name='ai_tpl_lookup_idx'), models.Index(fields=['active', 'language', 'style', 'category'], name='ai_tpl_style_idx')],
            },
        ),
    ]
