# Generated by Django 5.2.15 on 2026-06-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_client_id', models.CharField(blank=True, help_text='OAuth 2.0 Client ID from Google Cloud Console.', max_length=255)),
                ('google_client_secret', models.CharField(blank=True, help_text='OAuth 2.0 Client secret. Leave blank when saving to keep the current value.', max_length=255)),
                ('google_redirect_uri', models.URLField(blank=True, help_text='Backend callback URL, e.g. https://duobackend.onrender.com/api/auth/google/callback/', max_length=500)),
                ('google_allowed_redirect_uris', models.TextField(blank=True, help_text='Comma-separated redirect URIs allowed for token exchange (include web and mobile callbacks).')),
                ('email_host', models.CharField(blank=True, default='smtp.gmail.com', max_length=255)),
                ('email_port', models.PositiveIntegerField(blank=True, default=587, null=True)),
                ('email_use_tls', models.BooleanField(blank=True, default=True, null=True)),
                ('email_host_user', models.CharField(blank=True, max_length=255)),
                ('email_host_password', models.CharField(blank=True, help_text='SMTP password or app password. Leave blank when saving to keep the current value.', max_length=255)),
                ('default_from_email', models.CharField(blank=True, help_text='Sender address, e.g. "Duo <noreply@yourdomain.com>".', max_length=255)),
                ('esewa_product_code', models.CharField(blank=True, help_text='Merchant product code (EPAYTEST for sandbox).', max_length=64)),
                ('esewa_secret_key', models.CharField(blank=True, help_text='HMAC secret for payment signatures. Leave blank when saving to keep the current value.', max_length=255)),
                ('esewa_form_url', models.URLField(blank=True, help_text='eSewa payment form URL (sandbox or production).', max_length=500)),
                ('esewa_status_url', models.URLField(blank=True, help_text='eSewa transaction status API base URL.', max_length=500)),
                ('esewa_success_url', models.URLField(blank=True, help_text='Backend success callback, e.g. https://duobackend.onrender.com/api/subscriptions/esewa/success/', max_length=500)),
                ('esewa_failure_url', models.URLField(blank=True, help_text='Backend failure callback.', max_length=500)),
                ('cloudinary_cloud_name', models.CharField(blank=True, max_length=128)),
                ('cloudinary_api_key', models.CharField(blank=True, max_length=128)),
                ('cloudinary_api_secret', models.CharField(blank=True, help_text='Leave blank when saving to keep the current value.', max_length=255)),
                ('cloudinary_upload_preset', models.CharField(blank=True, max_length=128)),
                ('cloudinary_profile_folder', models.CharField(blank=True, default='duo/profile_photos', max_length=255)),
                ('cloudinary_chat_folder', models.CharField(blank=True, default='duo/chat_media', max_length=255)),
                ('cloudinary_verification_folder', models.CharField(blank=True, default='duo/verification_selfies', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integration settings',
                'verbose_name_plural': 'Integration settings',
            },
        ),
    ]
