# Generated by Django 5.2.15 on 2026-06-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0003_brevo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_brand_logo_url',
            field=models.URLField(blank=True, help_text='Logo URL for HTML email templates.', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_brand_primary_color',
            field=models.CharField(blank=True, default='#6366f1', help_text='Brand accent color for email templates (hex).', max_length=16),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_footer_text',
            field=models.CharField(blank=True, default='© SajiloWork. All rights reserved.', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_from_name',
            field=models.CharField(blank=True, default='SajiloWork', help_text='Default sender display name.', max_length=128),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_social_links',
            field=models.TextField(blank=True, help_text='Optional footer links (one per line: Label|https://url).'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_use_ssl',
            field=models.BooleanField(blank=True, default=False, help_text='Use SSL on connect (port 465). Leave off for STARTTLS on port 587.', null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_from_email',
            field=models.CharField(blank=True, help_text='Verified sender, e.g. "SajiloWork <noreply@yourdomain.com>".', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_delivery',
            field=models.CharField(choices=[('smtp', 'Brevo SMTP (recommended — smtp-relay.brevo.com:587)'), ('brevo', 'Brevo API (HTTPS fallback when SMTP is blocked)'), ('resend', 'Resend API')], default='smtp', help_text='Primary email provider. SMTP uses Brevo relay; API is used as automatic fallback.', max_length=16),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_host',
            field=models.CharField(blank=True, default='smtp-relay.brevo.com', help_text='SMTP relay host (Brevo: smtp-relay.brevo.com).', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='Brevo SMTP key. Leave blank when saving to keep the current value.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_host_user',
            field=models.CharField(blank=True, help_text='Brevo SMTP login email.', max_length=255),
        ),
    ]
