# Generated by Django 5.2.15 on 2026-07-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0005_sitesettings_openweather_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='fcm_enabled',
            field=models.BooleanField(default=False, help_text='Enable web and mobile push notifications via Firebase Cloud Messaging.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fcm_vapid_key',
            field=models.CharField(blank=True, help_text='Web Push certificate public key from Firebase → Cloud Messaging → Web configuration.', max_length=512),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='firebase_api_key',
            field=models.CharField(blank=True, help_text='Web API key from Firebase Console → Project settings → Your apps.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='firebase_app_id',
            field=models.CharField(blank=True, help_text='Firebase web app ID (1:...:web:...).', max_length=128),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='firebase_auth_domain',
            field=models.CharField(blank=True, help_text='e.g. your-project.firebaseapp.com', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='firebase_messaging_sender_id',
            field=models.CharField(blank=True, help_text='Messaging sender ID (numeric) from Firebase web app config.', max_length=64),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='firebase_project_id',
            field=models.CharField(blank=True, help_text='Firebase project ID from Project settings.', max_length=128),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='firebase_service_account_json',
            field=models.TextField(blank=True, help_text='Service account JSON with Firebase Cloud Messaging Admin role. Leave blank when saving to keep the current value.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_host_user',
            field=models.CharField(blank=True, help_text='Copy the exact SMTP login from Brevo → SMTP & API → SMTP tab (may be your email or something@smtp-brevo.com — do not guess).', max_length=255),
        ),
    ]
