# Generated by Django 5.2.15 on 2026-08-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0009_webrtc_stun_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='chat_backend',
            field=models.CharField(choices=[('django', 'Django (built-in chat app)'), ('microservice', 'Go microservice (chat-service)')], default='django', help_text='Which backend serves chat traffic. Switching takes effect for new page loads within a few minutes (cached) — no redeploy needed on either side.', max_length=16),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_service_public_url',
            field=models.URLField(blank=True, help_text='Public base URL of chat-service (e.g. https://chat.duoapp.com/api), used by the frontend when chat_backend=microservice. Leave blank to fall back to CHAT_SERVICE_PUBLIC_URL / CHAT_SERVICE_URL from environment.', max_length=500),
        ),
    ]
