# Generated by Django 5.2.15 on 2026-09-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0010_sitesettings_chat_backend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='email_delivery',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='email_relay_secret',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='nodemailer_relay_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='resend_api_key',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', help_text='Google SMTP host, e.g. smtp.gmail.com.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='Google App Password (16 characters, requires 2-Step Verification). Leave blank when saving to keep the current value.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_host_user',
            field=models.CharField(blank=True, help_text='Full Gmail / Google Workspace address, e.g. you@gmail.com.', max_length=255),
        ),
    ]
