# Generated by Django 5.2.15 on 2026-09-26 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0011_remove_nodemailer_resend_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='brevo_api_key',
        ),
    ]
