# Generated by Django 5.2.15 on 2026-10-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0012_remove_brevo_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_currency',
            field=models.CharField(blank=True, default='npr', help_text='ISO currency code charged by Stripe. 1 unit of this currency = 1 coin.', max_length=3),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_enabled',
            field=models.BooleanField(default=False, help_text='Show “Pay with card (Stripe)” on the wallet page.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, help_text='Publishable key (pk_test_… or pk_live_…) from dashboard.stripe.com/apikeys.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_secret_key',
            field=models.CharField(blank=True, help_text='Secret key (sk_test_… or sk_live_…). Leave blank when saving to keep the current value.', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_webhook_secret',
            field=models.CharField(blank=True, help_text='Webhook signing secret (whsec_…) for /api/subscriptions/stripe/webhook/.', max_length=500),
        ),
    ]
