# Generated by Django 5.2.15 on 2026-06-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEventSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('registration_otp', 'Registration verification OTP'), ('password_reset_otp', 'Password reset OTP'), ('welcome', 'Welcome email'), ('login_verification', 'Login verification'), ('email_change', 'Email change verification'), ('subscription_confirmed', 'Subscription payment confirmed'), ('subscription_failed', 'Subscription payment failed'), ('match_notification', 'New match notification'), ('admin_announcement', 'Admin announcement'), ('contact_form', 'Contact form'), ('account_status', 'Account status change'), ('generic', 'Generic transactional')], max_length=64, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('subject_template', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email event',
                'verbose_name_plural': 'Email events',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('registration_otp', 'Registration verification OTP'), ('password_reset_otp', 'Password reset OTP'), ('welcome', 'Welcome email'), ('login_verification', 'Login verification'), ('email_change', 'Email change verification'), ('subscription_confirmed', 'Subscription payment confirmed'), ('subscription_failed', 'Subscription payment failed'), ('match_notification', 'New match notification'), ('admin_announcement', 'Admin announcement'), ('contact_form', 'Contact form'), ('account_status', 'Account status change'), ('generic', 'Generic transactional')], db_index=True, max_length=64)),
                ('recipient', models.EmailField(db_index=True, max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('smtp', 'SMTP'), ('brevo_api', 'Brevo API'), ('resend_api', 'Resend API')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('retried', 'Retried')], db_index=True, max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=1)),
                ('error_message', models.TextField(blank=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Email log',
                'verbose_name_plural': 'Email logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('registration_otp', 'Registration verification OTP'), ('password_reset_otp', 'Password reset OTP'), ('welcome', 'Welcome email'), ('login_verification', 'Login verification'), ('email_change', 'Email change verification'), ('subscription_confirmed', 'Subscription payment confirmed'), ('subscription_failed', 'Subscription payment failed'), ('match_notification', 'New match notification'), ('admin_announcement', 'Admin announcement'), ('contact_form', 'Contact form'), ('account_status', 'Account status change'), ('generic', 'Generic transactional')], max_length=64, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('text_body', models.TextField()),
                ('html_body', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email template',
                'verbose_name_plural': 'Email templates',
            },
        ),
    ]
