from django.urls import path

from .views import (
    BackupCodesRegenerateView,
    BackupCodesStatusView,
    BiometricDisableView,
    BiometricEnableView,
    BiometricLoginView,
    BiometricStatusView,
    DeviceListView,
    DeviceLogoutView,
    DeviceRenameView,
    DeviceTrustView,
    DeviceUntrustView,
    LoginHistoryView,
    LogoutAllDevicesView,
    PasswordVerifyView,
    SecurityEventReadView,
    SecurityEventsReadAllView,
    SecurityEventsView,
    SecurityOverviewView,
    TwoFactorDisableView,
    TwoFactorEnableView,
    TwoFactorLoginSendOtpView,
    TwoFactorLoginView,
    TwoFactorSetupEmailView,
    TwoFactorSetupTotpView,
)

urlpatterns = [
    path("overview/", SecurityOverviewView.as_view(), name="security_overview"),
    path("password/verify/", PasswordVerifyView.as_view(), name="security_password_verify"),
    path("2fa/setup/totp/", TwoFactorSetupTotpView.as_view(), name="security_2fa_setup_totp"),
    path("2fa/setup/email/", TwoFactorSetupEmailView.as_view(), name="security_2fa_setup_email"),
    path("2fa/enable/", TwoFactorEnableView.as_view(), name="security_2fa_enable"),
    path("2fa/disable/", TwoFactorDisableView.as_view(), name="security_2fa_disable"),
    path("2fa/backup-codes/", BackupCodesStatusView.as_view(), name="security_backup_codes_status"),
    path("2fa/backup-codes/regenerate/", BackupCodesRegenerateView.as_view(), name="security_backup_codes_regenerate"),
    path("2fa/login/", TwoFactorLoginView.as_view(), name="security_2fa_login"),
    path("2fa/login/send-otp/", TwoFactorLoginSendOtpView.as_view(), name="security_2fa_login_send_otp"),
    path("devices/", DeviceListView.as_view(), name="security_devices"),
    path("devices/<int:device_id>/rename/", DeviceRenameView.as_view(), name="security_device_rename"),
    path("devices/<int:device_id>/trust/", DeviceTrustView.as_view(), name="security_device_trust"),
    path("devices/<int:device_id>/untrust/", DeviceUntrustView.as_view(), name="security_device_untrust"),
    path("devices/<int:device_id>/logout/", DeviceLogoutView.as_view(), name="security_device_logout"),
    path("devices/logout-all/", LogoutAllDevicesView.as_view(), name="security_logout_all"),
    path("login-history/", LoginHistoryView.as_view(), name="security_login_history"),
    path("events/", SecurityEventsView.as_view(), name="security_events"),
    path("events/read-all/", SecurityEventsReadAllView.as_view(), name="security_events_read_all"),
    path("events/<int:event_id>/read/", SecurityEventReadView.as_view(), name="security_event_read"),
    path("biometric/enable/", BiometricEnableView.as_view(), name="security_biometric_enable"),
    path("biometric/disable/", BiometricDisableView.as_view(), name="security_biometric_disable"),
    path("biometric/status/", BiometricStatusView.as_view(), name="security_biometric_status"),
    path("biometric/login/", BiometricLoginView.as_view(), name="security_biometric_login"),
]
