# Generated by Django 5.2.12 on 2026-04-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user1_last_typed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user2_last_typed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
