# Generated by Django 5.2.15 on 2026-10-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationpreference',
            name='filter_offensive',
            field=models.BooleanField(default=True),
        ),
    ]
