# Generated by Django 5.2.15 on 2026-06-22 03:13

import django.db.models.deletion
import photo_verification.constants
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('image_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('face_detected', models.BooleanField(default=False)),
                ('face_count', models.PositiveSmallIntegerField(default=0)),
                ('face_centered', models.BooleanField(default=False)),
                ('blur_score', models.FloatField(default=0.0)),
                ('brightness_score', models.FloatField(default=0.0)),
                ('resolution_passed', models.BooleanField(default=False)),
                ('image_width', models.PositiveIntegerField(default=0)),
                ('image_height', models.PositiveIntegerField(default=0)),
                ('quality_score', models.PositiveSmallIntegerField(default=0)),
                ('ai_generated_probability', models.FloatField(default=0.0)),
                ('duplicate_probability', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('WARNING', 'WARNING'), ('REJECTED', 'REJECTED')], default=photo_verification.constants.PhotoStatus['REJECTED'], max_length=16)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('rejection_reasons', models.JSONField(blank=True, default=list)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this was uploaded as the primary profile photo.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Photo analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='photo_verif_user_id_e093e7_idx'), models.Index(fields=['status'], name='photo_verif_status_5795d4_idx')],
            },
        ),
    ]
