# Generated by Django 5.2.15 on 2026-06-22 03:25

import django.db.models.deletion
import photo_verification.constants
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_verification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField(max_length=1000)),
                ('embedding_vector', models.JSONField(default=list)),
                ('quality_score', models.PositiveSmallIntegerField(default=0)),
                ('face_count', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_embeddings', to='photo_verification.photoanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='photo_verif_user_id_2b0b83_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.UUIDField(db_index=True, unique=True)),
                ('profile_photo_url', models.URLField(blank=True, max_length=1000)),
                ('selfie_photo_url', models.URLField(blank=True, max_length=1000)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('liveness_score', models.FloatField(default=0.0)),
                ('fraud_probability', models.FloatField(default=0.0)),
                ('verification_status', models.CharField(choices=[('PENDING', 'PENDING'), ('VERIFIED', 'VERIFIED'), ('REJECTED', 'REJECTED'), ('UNDER_REVIEW', 'UNDER_REVIEW')], default=photo_verification.constants.VerificationStatus['PENDING'], max_length=16)),
                ('liveness_data', models.JSONField(blank=True, default=dict)),
                ('rejection_reasons', models.JSONField(blank=True, default=list)),
                ('review_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='photo_verif_user_id_e8ffd8_idx'), models.Index(fields=['verification_status'], name='photo_verif_verific_e3a399_idx'), models.Index(fields=['session_token'], name='photo_verif_session_1fb39a_idx')],
            },
        ),
    ]
