# Generated by Django 5.2.15 on 2026-09-08 17:51

import django.db.models.deletion
import photo_verification.constants
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_verification', '0003_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('MANUAL_REVIEW', 'MANUAL_REVIEW')], default=photo_verification.constants.ModerationStatus['PENDING'], max_length=16)),
                ('rejection_reason', models.CharField(blank=True, help_text='User-facing, friendly reason only — never a raw category or score.', max_length=200)),
                ('rejection_category', models.CharField(blank=True, choices=[('nudity', 'nudity'), ('violence', 'violence'), ('weapon', 'weapon'), ('hate_symbol', 'hate_symbol'), ('drugs', 'drugs'), ('non_photo_content', 'non_photo_content'), ('quality', 'quality'), ('other', 'other')], help_text='Internal-only classification. Never exposed via the API.', max_length=32)),
                ('moderation_source', models.CharField(blank=True, help_text='e.g. "nudenet+clip+quality_pipeline" or "manual:<username>".', max_length=64)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('photo_analysis', models.ForeignKey(blank=True, help_text='Quality/face/duplicate signals for this upload (reused, not duplicated).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_photos', to='photo_verification.photoanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='photo_verif_user_id_55af30_idx'), models.Index(fields=['user', 'order'], name='photo_verif_user_id_a6ff51_idx'), models.Index(fields=['url'], name='photo_verif_url_b9706c_idx')],
            },
        ),
    ]
