# Generated by Django 5.2.12 on 2026-04-10 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('location', models.CharField(default='Kathmandu, Nepal', max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('religion', models.CharField(blank=True, choices=[('Hindu', 'Hindu'), ('Buddhist', 'Buddhist'), ('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Other', 'Other')], max_length=20)),
                ('education', models.CharField(blank=True, max_length=300)),
                ('occupation', models.CharField(blank=True, max_length=300)),
                ('work_preference', models.CharField(blank=True, choices=[('Private', 'Private Sector'), ('Government', 'Government'), ('Business', 'Business/Self-Employed'), ('NotWorking', 'Not Working')], max_length=20)),
                ('lifestyle_tags', models.JSONField(blank=True, default=list)),
                ('photo_url', models.URLField(blank=True, max_length=1000)),
                ('pref_age_min', models.IntegerField(default=22)),
                ('pref_age_max', models.IntegerField(default=35)),
                ('pref_min_height', models.CharField(blank=True, default='5\'2" (157cm)', max_length=20)),
                ('pref_occupation', models.CharField(blank=True, default='Professional Degree', max_length=200)),
                ('pref_values', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_onboarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
