# Generated by Django 5.2.15 on 2026-09-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_live_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='app_language',
            field=models.CharField(choices=[('en', 'English'), ('ne', 'नेपाली (Nepali)')], default='en', max_length=8),
        ),
        migrations.AddField(
            model_name='profile',
            name='app_region',
            field=models.CharField(blank=True, default='Nepal', max_length=100),
        ),
    ]
