# Generated by Django 5.2.15 on 2026-09-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_app_language_profile_app_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, choices=[('Hindu', 'Hindu'), ('Buddhist', 'Buddhist'), ('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Kirat', 'Kirat'), ('Sikh', 'Sikh'), ('Jain', 'Jain'), ('Jewish', 'Jewish'), ('Non-religious', 'Non-religious'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_preference',
            field=models.CharField(blank=True, choices=[('Private', 'Private Sector'), ('Government', 'Government'), ('Business', 'Business/Self-Employed'), ('Freelancer', 'Freelancer'), ('Student', 'Student'), ('Retired', 'Retired'), ('NotWorking', 'Not Working')], max_length=20),
        ),
    ]
