# Generated by Django 5.2.15 on 2026-09-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_religion_alter_profile_work_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pref_expand_age',
            field=models.BooleanField(default=True, help_text='Show people slightly outside the age range when nobody is left inside it.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pref_expand_distance',
            field=models.BooleanField(default=True, help_text='Show people further away when nobody is left within the distance limit.'),
        ),
    ]
