# Generated by Django 5.2.15 on 2026-07-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='backupcode',
            new_name='security_ba_user_id_b3650f_idx',
            old_name='security_ba_user_id_3c8e2a_idx',
        ),
        migrations.RenameIndex(
            model_name='biometriccredential',
            new_name='security_bi_user_id_8e5d96_idx',
            old_name='security_bi_user_id_5a9d1f_idx',
        ),
        migrations.RenameIndex(
            model_name='loginhistory',
            new_name='security_lo_user_id_30ce75_idx',
            old_name='security_lo_user_id_2e7b4c_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='security_se_user_id_8d1054_idx',
            old_name='security_se_user_id_4d8a2b_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='security_se_user_id_c8a3d7_idx',
            old_name='security_se_user_id_9f1c3e_idx',
        ),
        migrations.RenameIndex(
            model_name='userdevice',
            new_name='security_us_user_id_2894bc_idx',
            old_name='security_us_user_id_6f0f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='userdevice',
            new_name='security_us_user_id_75c22a_idx',
            old_name='security_us_user_id_8a2c4e_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='security_us_user_id_9aa362_idx',
            old_name='security_us_user_id_1b3d2a_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='security_us_refresh_e55c07_idx',
            old_name='security_us_refresh_7c5e1f_idx',
        ),
    ]
