# Generated by Django 5.2.15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.CharField(help_text="Semantic version, e.g. 1.0.8", max_length=32)),
                ("build_number", models.PositiveIntegerField(help_text="Monotonic build number, e.g. 108")),
                (
                    "platform",
                    models.CharField(
                        choices=[("android", "Android"), ("ios", "iOS")],
                        default="android",
                        max_length=16,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("stable", "Stable"), ("beta", "Beta")],
                        default="stable",
                        max_length=16,
                    ),
                ),
                ("apk_file", models.FileField(blank=True, null=True, upload_to="apk/")),
                (
                    "apk_url",
                    models.URLField(
                        blank=True,
                        help_text="Public HTTPS URL when APK is hosted on S3/R2/GitHub.",
                        max_length=1024,
                    ),
                ),
                ("release_notes", models.JSONField(blank=True, default=list)),
                (
                    "minimum_version",
                    models.CharField(
                        blank=True,
                        help_text="Users below this version must update when force_update is enabled.",
                        max_length=32,
                    ),
                ),
                ("force_update", models.BooleanField(default=False)),
                ("soft_update", models.BooleanField(default=True)),
                ("emergency_update", models.BooleanField(default=False)),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one active release per platform/channel.",
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-build_number", "-published_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["platform", "channel", "is_active"], name="update_appv_plat_ch_act_idx"),
                    models.Index(fields=["platform", "build_number"], name="update_appv_plat_build_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("platform", "channel", "version", "build_number"),
                        name="update_unique_platform_channel_version_build",
                    )
                ],
            },
        ),
    ]
