# Generated by Django 5.2.15 on 2026-07-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appversion',
            new_name='update_appv_platfor_4ca8a4_idx',
            old_name='update_appv_plat_ch_act_idx',
        ),
        migrations.RenameIndex(
            model_name='appversion',
            new_name='update_appv_platfor_15f44c_idx',
            old_name='update_appv_plat_build_idx',
        ),
    ]
