# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("update", "0002_rename_update_appv_plat_ch_act_idx_update_appv_platfor_4ca8a4_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appversion",
            name="release_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Customer-facing release title shown in the update dialog.",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="appversion",
            name="release_notes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Customer-facing bullets. Technical GitHub release body must not be pasted here.",
            ),
        ),
    ]
