"""Default avatar configuration schema (v2 modular character creator)."""

DEFAULT_AVATAR_CONFIG = {
    "version": 2,
    "gender": "",
    "modelSource": "modular",
    "modelUrl": "",
    "facePreset": 1,
    "faceShape": 50,
    "faceWidth": 50,
    "faceHeight": 50,
    "jaw": 50,
    "jawWidth": 50,
    "chin": 50,
    "chinLength": 50,
    "cheeks": 50,
    "cheekFullness": 50,
    "skinTone": 2,
    "skinTexture": 40,
    "freckles": 0,
    "moles": 0,
    "acne": 0,
    "wrinkles": 10,
    "shine": 30,
    "smoothness": 60,
    "eyeShape": 1,
    "eyeSize": 50,
    "eyeSpacing": 50,
    "eyeAngle": 50,
    "eyeColor": "#3b5b8a",
    "pupilSize": 50,
    "eyelashes": 45,
    "eyelidShape": 50,
    "browStyle": 1,
    "browThickness": 50,
    "browLength": 50,
    "browPosition": 50,
    "browRotation": 50,
    "browColor": "#2c1810",
    "noseWidth": 50,
    "noseHeight": 50,
    "noseLength": 50,
    "noseBridge": 50,
    "noseTip": 50,
    "nostrilSize": 50,
    "lipShape": 1,
    "lipSize": 50,
    "upperLip": 50,
    "lowerLip": 50,
    "smile": 35,
    "mouthWidth": 50,
    "lipColor": "#c45c6a",
    "teethStyle": 0,
    "smileIntensity": 40,
    "earSize": 50,
    "earRotation": 50,
    "earShape": 50,
    "beardStyle": 0,
    "beardLength": 30,
    "beardThickness": 40,
    "mustache": 0,
    "sideburns": 0,
    "facialHairColor": "#2c1810",
    "hairStyle": 2,
    "hairColor": "#3d2314",
    "hairHighlight": "#6b4423",
    "hairLength": 50,
    "hairVolume": 50,
    "hairShine": 40,
    "bodyHeight": 50,
    "bodyWeight": 45,
    "muscle": 40,
    "bodyFat": 30,
    "shoulderWidth": 50,
    "chestSize": 50,
    "waistSize": 45,
    "hipSize": 50,
    "armThickness": 45,
    "legThickness": 45,
    "handSize": 50,
    "footSize": 50,
    "bodyBuild": "average",
    "shirtStyle": 1,
    "shirtColor": "#ec4899",
    "shirtMaterial": 0,
    "jacketStyle": 0,
    "jacketColor": "#334155",
    "pantsStyle": 1,
    "pantsColor": "#1e293b",
    "pantsMaterial": 0,
    "shoeStyle": 1,
    "shoeColor": "#111827",
    "outerwearStyle": 0,
    "outerwearColor": "#1e293b",
    "glassesStyle": 0,
    "hatStyle": 0,
    "earringStyle": 0,
    "necklaceStyle": 0,
    "watchStyle": 0,
    "ringStyle": 0,
    "braceletStyle": 0,
    "backpackStyle": 0,
    "scarfStyle": 0,
    "idleAnimation": "idle",
}


def merge_avatar_config(raw: dict | None) -> dict:
    base = dict(DEFAULT_AVATAR_CONFIG)
    if not isinstance(raw, dict):
        return base
    for key, value in raw.items():
        base[key] = value
    base["version"] = 2
    return base
