# Generated by Django 5.2.15 on 2026-07-01 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_visited_at', models.DateTimeField(auto_now=True)),
                ('viewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_visits_received', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_visits_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_visited_at'],
                'indexes': [models.Index(fields=['viewed_user', '-last_visited_at'], name='matching_pr_viewed__d8fc41_idx')],
                'unique_together': {('viewer', 'viewed_user')},
            },
        ),
    ]
