# Generated by Django 5.2.15 on 2026-09-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_like_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ai_insights',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='ai_insights_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='ai_insights_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
