# Generated by Django 5.2.15 on 2026-09-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_match_ai_insights'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='duo-match', max_length=40)),
                ('payload', models.JSONField()),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('samples', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
