# Generated by Django 5.2.15 on 2026-06-21 19:32

import django.core.validators
from django.db import migrations, models


DEFAULT_PLANS = [
    {
        "plan_id": "duo_premium_7d",
        "name": "7-Day Pass",
        "description": "Unlock Liked you for one week.",
        "duration_days": 7,
        "amount": "149.00",
        "badge": "",
        "sort_order": 1,
        "is_default": False,
    },
    {
        "plan_id": "duo_premium_30d",
        "name": "30-Day Pass",
        "description": "Unlock Liked you for one month.",
        "duration_days": 30,
        "amount": "499.00",
        "badge": "Popular",
        "sort_order": 2,
        "is_default": True,
    },
    {
        "plan_id": "duo_premium_90d",
        "name": "90-Day Pass",
        "description": "Best value — three months of Premium.",
        "duration_days": 90,
        "amount": "999.00",
        "badge": "Best value",
        "sort_order": 3,
        "is_default": False,
    },
]


def seed_who_liked_you_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model("subscriptions", "SubscriptionPlan")
    for plan in DEFAULT_PLANS:
        SubscriptionPlan.objects.update_or_create(
            plan_id=plan["plan_id"],
            defaults={
                "name": plan["name"],
                "description": plan["description"],
                "feature": "who_liked_you",
                "duration_days": plan["duration_days"],
                "amount": plan["amount"],
                "currency": "NPR",
                "badge": plan["badge"],
                "is_active": True,
                "is_default": plan["is_default"],
                "sort_order": plan["sort_order"],
            },
        )


def unseed_who_liked_you_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model("subscriptions", "SubscriptionPlan")
    SubscriptionPlan.objects.filter(
        plan_id__in=[plan["plan_id"] for plan in DEFAULT_PLANS]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('feature', models.CharField(choices=[('who_liked_you', 'Who liked you')], default='who_liked_you', max_length=32)),
                ('duration_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='NPR', max_length=8)),
                ('badge', models.CharField(blank=True, choices=[('', 'None'), ('Popular', 'Popular'), ('Best value', 'Best value')], default='', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Used when no plan is selected (typically the 30-day pass).')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Who liked you plan',
                'verbose_name_plural': 'Who liked you plans',
                'ordering': ['sort_order', 'duration_days', 'amount'],
            },
        ),
        migrations.RunPython(seed_who_liked_you_plans, unseed_who_liked_you_plans),
    ]
