# Generated by Django 5.2.15 on 2026-09-09 18:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('esewa', 'eSewa'), ('wallet', 'Wallet balance')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending'), ('failed', 'Failed')], default='complete', max_length=16),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
