# Generated by Django 5.2.15 on 2026-09-11 07:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_backfill_wallet_transaction_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('top_up', 'Top up'), ('purchase', 'Purchase'), ('adjustment', 'Adjustment'), ('gift_redeem', 'Gift card redeemed')], max_length=16),
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('code_last4', models.CharField(blank=True, default='', help_text='Last 4 characters of the code, for identifying a card in admin without storing the full code.', max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('1000000'))])),
                ('status', models.CharField(choices=[('unused', 'Unused'), ('redeemed', 'Redeemed'), ('revoked', 'Revoked')], default='unused', max_length=16)),
                ('note', models.CharField(blank=True, default='', help_text='Internal note — campaign name, batch, recipient, etc. Never shown to users.', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giftcards_created', to=settings.AUTH_USER_MODEL)),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giftcards_redeemed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='giftcard_status_idx')],
            },
        ),
    ]
