# Generated by Django 5.2.15 on 2026-09-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_wallettransaction_type_giftcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('esewa', 'eSewa'), ('wallet', 'Wallet balance'), ('gift', 'Gift card')], default='', max_length=16),
        ),
    ]
