# Generated by Django 5.2.15 on 2026-09-27 10:42

from django.db import migrations, models

FEATURE_CHOICES = [
    ('who_liked_you', 'Who liked you'),
    ('visited_you', 'Visited you'),
    ('all', 'All premium features (legacy pass)'),
]

VISITED_YOU_PLANS = [
    {
        "plan_id": "visited_you_7d",
        "name": "7-Day Visitors Pass",
        "description": "See who visited your profile for one week.",
        "duration_days": 7,
        "amount": "149.00",
        "badge": "",
        "sort_order": 1,
        "is_default": False,
    },
    {
        "plan_id": "visited_you_30d",
        "name": "30-Day Visitors Pass",
        "description": "See who visited your profile for one month.",
        "duration_days": 30,
        "amount": "499.00",
        "badge": "Popular",
        "sort_order": 2,
        "is_default": True,
    },
    {
        "plan_id": "visited_you_90d",
        "name": "90-Day Visitors Pass",
        "description": "Best value: three months of profile visitors.",
        "duration_days": 90,
        "amount": "999.00",
        "badge": "Best value",
        "sort_order": 3,
        "is_default": False,
    },
]


def seed_visited_you_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model("subscriptions", "SubscriptionPlan")
    for plan in VISITED_YOU_PLANS:
        # get_or_create: never overwrite prices an admin already edited.
        SubscriptionPlan.objects.get_or_create(
            plan_id=plan["plan_id"],
            defaults={
                "name": plan["name"],
                "description": plan["description"],
                "feature": "visited_you",
                "duration_days": plan["duration_days"],
                "amount": plan["amount"],
                "currency": "NPR",
                "badge": plan["badge"],
                "is_active": True,
                "is_default": plan["is_default"],
                "sort_order": plan["sort_order"],
            },
        )


def unseed_visited_you_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model("subscriptions", "SubscriptionPlan")
    SubscriptionPlan.objects.filter(
        plan_id__in=[plan["plan_id"] for plan in VISITED_YOU_PLANS]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_alter_wallettransaction_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedYouPlan',
            fields=[
            ],
            options={
                'verbose_name': 'Visited you plan',
                'verbose_name_plural': 'Visited you plans',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('subscriptions.subscriptionplan',),
        ),
        migrations.CreateModel(
            name='WhoLikedYouPlan',
            fields=[
            ],
            options={
                'verbose_name': 'Who liked you plan',
                'verbose_name_plural': 'Who liked you plans',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('subscriptions.subscriptionplan',),
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['sort_order', 'duration_days', 'amount'], 'verbose_name': 'Subscription plan', 'verbose_name_plural': 'Subscription plans'},
        ),
        # Existing passes unlocked both lists, so backfill them as "all".
        migrations.AddField(
            model_name='subscriptionpayment',
            name='feature',
            field=models.CharField(choices=FEATURE_CHOICES, default='all', help_text='Premium list this pass unlocks.', max_length=32),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='feature',
            field=models.CharField(choices=FEATURE_CHOICES, default='who_liked_you', help_text='Premium list this pass unlocks.', max_length=32),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='feature',
            field=models.CharField(choices=[('who_liked_you', 'Who liked you'), ('visited_you', 'Visited you')], default='who_liked_you', max_length=32),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Pre-selected plan for its feature (typically the 30-day pass).'),
        ),
        migrations.RunPython(seed_visited_you_plans, unseed_visited_you_plans),
    ]
