# Generated by Django 5.2.15 on 2026-09-27 12:06

from django.db import migrations, models

REWIND_PLANS = [
    ("rewind_7d", "7-Day Rewind", "Undo swipes for one week.", 7, "99.00", "", 1, False),
    ("rewind_30d", "30-Day Rewind", "Undo swipes for one month.", 30, "299.00", "Popular", 2, True),
    ("rewind_90d", "90-Day Rewind", "Best value: three months of rewinds.", 90, "699.00", "Best value", 3, False),
]


def seed_rewind_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model("subscriptions", "SubscriptionPlan")
    for plan_id, name, description, days, amount, badge, order, is_default in REWIND_PLANS:
        # get_or_create: never overwrite prices an admin already edited.
        SubscriptionPlan.objects.get_or_create(
            plan_id=plan_id,
            defaults={
                "name": name,
                "description": description,
                "feature": "rewind",
                "duration_days": days,
                "amount": amount,
                "currency": "NPR",
                "badge": badge,
                "is_active": True,
                "is_default": is_default,
                "sort_order": order,
            },
        )


def unseed_rewind_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model("subscriptions", "SubscriptionPlan")
    SubscriptionPlan.objects.filter(plan_id__in=[row[0] for row in REWIND_PLANS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_visited_you_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewindPlan',
            fields=[
            ],
            options={
                'verbose_name': 'Rewind plan',
                'verbose_name_plural': 'Rewind plans',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('subscriptions.subscriptionplan',),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='feature',
            field=models.CharField(choices=[('who_liked_you', 'Who liked you'), ('visited_you', 'Visited you'), ('rewind', 'Rewind'), ('all', 'All premium features (legacy pass)')], default='who_liked_you', help_text='Premium list this pass unlocks.', max_length=32),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='feature',
            field=models.CharField(choices=[('who_liked_you', 'Who liked you'), ('visited_you', 'Visited you'), ('rewind', 'Rewind')], default='who_liked_you', max_length=32),
        ),
        migrations.RunPython(seed_rewind_plans, unseed_rewind_plans),
    ]
