# Generated by Django 5.2.15 on 2026-09-27 12:28

from django.db import migrations, models

UNLIMITED_LIKES_PLANS = [
    ("unlimited_likes_7d", "7-Day Unlimited Likes", "Like as many people as you want for one week.", 7, "199.00", "", 1, False),
    ("unlimited_likes_30d", "30-Day Unlimited Likes", "No Like limit for one month.", 30, "599.00", "Popular", 2, True),
    ("unlimited_likes_90d", "90-Day Unlimited Likes", "Best value: three months without a Like limit.", 90, "1299.00", "Best value", 3, False),
]


def seed_unlimited_likes_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model("subscriptions", "SubscriptionPlan")
    for plan_id, name, description, days, amount, badge, order, is_default in UNLIMITED_LIKES_PLANS:
        # get_or_create: never overwrite prices an admin already edited.
        SubscriptionPlan.objects.get_or_create(
            plan_id=plan_id,
            defaults={
                "name": name,
                "description": description,
                "feature": "unlimited_likes",
                "duration_days": days,
                "amount": amount,
                "currency": "NPR",
                "badge": badge,
                "is_active": True,
                "is_default": is_default,
                "sort_order": order,
            },
        )


def unseed_unlimited_likes_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model("subscriptions", "SubscriptionPlan")
    SubscriptionPlan.objects.filter(plan_id__in=[row[0] for row in UNLIMITED_LIKES_PLANS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_rewind_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnlimitedLikesPlan',
            fields=[
            ],
            options={
                'verbose_name': 'Unlimited likes plan',
                'verbose_name_plural': 'Unlimited likes plans',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('subscriptions.subscriptionplan',),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='feature',
            field=models.CharField(choices=[('who_liked_you', 'Who liked you'), ('visited_you', 'Visited you'), ('rewind', 'Rewind'), ('unlimited_likes', 'Unlimited likes'), ('all', 'All premium features (legacy pass)')], default='who_liked_you', help_text='Premium list this pass unlocks.', max_length=32),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='feature',
            field=models.CharField(choices=[('who_liked_you', 'Who liked you'), ('visited_you', 'Visited you'), ('rewind', 'Rewind'), ('unlimited_likes', 'Unlimited likes')], default='who_liked_you', max_length=32),
        ),
        migrations.RunPython(seed_unlimited_likes_plans, unseed_unlimited_likes_plans),
    ]
