# Generated by Django 5.2.15 on 2026-10-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_unlimited_likes_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettopup',
            name='provider',
            field=models.CharField(choices=[('esewa', 'eSewa'), ('stripe', 'Stripe')], default='esewa', max_length=16),
        ),
        migrations.AddField(
            model_name='wallettopup',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='wallettopup',
            name='stripe_session_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('esewa', 'eSewa'), ('stripe', 'Card (Stripe)'), ('wallet', 'Wallet balance'), ('gift', 'Gift card')], default='', max_length=16),
        ),
    ]
