# Generated by Django 5.2.15 on 2026-07-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationpreference_calls_enabled'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicetoken',
            new_name='notificatio_platfor_786102_idx',
            old_name='notificatio_platfor_a8e2c1_idx',
        ),
        migrations.RenameIndex(
            model_name='pushdeliverylog',
            new_name='notificatio_user_id_28e3e3_idx',
            old_name='notificatio_user_id_4f0b2a_idx',
        ),
        migrations.RenameIndex(
            model_name='pushdeliverylog',
            new_name='notificatio_status_23a7c8_idx',
            old_name='notificatio_status_9c1d3e_idx',
        ),
    ]
