# Generated by Django 5.2.15 on 2026-09-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_rename_notificatio_platfor_a8e2c1_idx_notificatio_platfor_786102_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='email_announcements',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_matches',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_payments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_verification',
            field=models.BooleanField(default=True),
        ),
    ]
